version: "3.9"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
  
  db:
    image: postgres:11
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=examplepassword